const PRODUCTS = [
  {
    id: 1,
    name: "Canapé Velours Milano",
    category: "Mobilier",
    price: 1290,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 124,
    emoji: "🛋️",
    color: "#8b5e3c",
    badges: ["new"],
    tab: "tendance",
    description: "Canapé 3 places en velours côtelé, pieds laiton brossé. Confort exceptionnel et style intemporel."
  },
  {
    id: 2,
    name: "Vase Céramique Artisanal",
    category: "Décoration",
    price: 89,
    originalPrice: 130,
    rating: 4.9,
    reviewCount: 87,
    emoji: "🏺",
    color: "#c9a96e",
    badges: ["sale"],
    tab: "promo",
    description: "Vase en céramique fait main par nos artisans. Glaçure bicolore unique, pièce exclusive."
  },
  {
    id: 3,
    name: "Table Basse Marbre & Laiton",
    category: "Mobilier",
    price: 649,
    originalPrice: null,
    rating: 4.7,
    reviewCount: 56,
    emoji: "🪨",
    color: "#e8e8e8",
    badges: ["popular"],
    tab: "tendance",
    description: "Table basse plateau marbre blanc, structure laiton. Dimensions: 120 x 60 x 45 cm."
  },
  {
    id: 4,
    name: "Lampe Suspension Rotin",
    category: "Luminaires",
    price: 245,
    originalPrice: 320,
    rating: 4.6,
    reviewCount: 43,
    emoji: "💡",
    color: "#c9a96e",
    badges: ["sale"],
    tab: "promo",
    description: "Suspension artisanale en rotin tressé, câble textile noir. Diamètre 50 cm."
  },
  {
    id: 5,
    name: "Miroir Arche Doré",
    category: "Décoration",
    price: 389,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 201,
    emoji: "🪞",
    color: "#c9a96e",
    badges: ["new", "popular"],
    tab: "nouveaute",
    description: "Miroir en arche avec cadre en métal doré mat. H:180 cm x L:75 cm. Livraison gratuite."
  },
  {
    id: 6,
    name: "Tapis Berbère Authentique",
    category: "Textiles",
    price: 520,
    originalPrice: null,
    rating: 4.8,
    reviewCount: 67,
    emoji: "🪗",
    color: "#e8d5b7",
    badges: [],
    tab: "tendance",
    description: "Tapis berbère tissé à la main au Maroc. 100% laine naturelle. 200 x 300 cm."
  },
  {
    id: 7,
    name: "Bibliothèque Modulaire Chêne",
    category: "Mobilier",
    price: 890,
    originalPrice: 1150,
    rating: 4.7,
    reviewCount: 38,
    emoji: "📚",
    color: "#8b5e3c",
    badges: ["sale"],
    tab: "promo",
    description: "Bibliothèque modulaire en chêne massif huilé. 6 modules ajustables. H:200 cm."
  },
  {
    id: 8,
    name: "Bougeoirs Bronze Trio",
    category: "Décoration",
    price: 125,
    originalPrice: null,
    rating: 4.9,
    reviewCount: 156,
    emoji: "🕯️",
    color: "#8b6914",
    badges: ["new"],
    tab: "nouveaute",
    description: "Set de 3 bougeoirs en laiton vieilli. Hauteurs: 15, 22, 30 cm. Design minimaliste."
  }
];

window.PRODUCTS = PRODUCTS;
